--maxGrad
CREATE VIEW `maxGrad` AS select `mg`.`MitgliedId` AS `MitgliedId`,max(`mg`.`GradId`) AS `Grade`,concat(`g`.`gKurz`,' ',`dd`.`DispKurz`) AS `CONCAT(``g``.``gKurz``, ' ', ``dd``.``DispKurz``)` from ((`mitgliedergrade` `mg` left join `grade` `g` on(`g`.`gradId` = `mg`.`GradId`)) left join `disziplinen` `dd` on(`dd`.`DispName` = `g`.`DispName`)) group by `mg`.`MitgliedId`,`dd`.`DispName` order by `mg`.`MitgliedId`; 
--maxgrad 	
CREATE VIEW `maxgrad` AS select `mg`.`MitgliedId` AS `MitgliedId`,max(`mg`.`GradId`) AS `Grad` from (`mitgliedergrade` `mg` left join `grade` `g` on(`g`.`gradId` = `mg`.`GradId`)) group by `mg`.`MitgliedId`,`g`.`DispName` order by `mg`.`MitgliedId`; 
--mitgliederliste 	
CREATE  VIEW `mitgliederliste` AS select `m`.`MitgliederId` AS `MitgliederId`,`m`.`MitgliedsNr` AS `MitgliedsNr`,`m`.`Vorname` AS `Vorname`,`m`.`Name` AS `Nachname`,`m`.`Funktion` AS `Funktion`,`m`.`PruefungZum` AS `PruefungZum`,concat(`m`.`Name`,', ',`m`.`Vorname`) AS `Name`,`m`.`Schulort` AS `Schulname`,`sl`.`LeiterName` AS `LeiterName`,coalesce(group_concat(distinct `scd`.`DispKurz` separator ', '),`m`.`Disziplin`) AS `DispName`,ifnull(group_concat(distinct concat(`sc`.`Schulname`,' ',`scd`.`DispKurz`) separator ', '),'.') AS `Vertrag`,group_concat(distinct concat(`g`.`gKurz`,' ',`dd`.`DispKurz`) separator ', ') AS `Grad`,`m`.`LetzteAenderung` AS `LetzteAenderung`,`m`.`LetztAendSifu` AS `LetztAendSifu`,`m`.`GeburtsDatum` AS `GeburtsDatum`,`m`.`Email` AS `Email`,`m`.`RecDeleted` AS `RecDeleted`,`s`.`SchulId` AS `SchulId`,`mgg`.`printed` AS `printed`,`mgg`.`mgID` AS `mgID` from (((((((((((`mitglieder` `m` left join `mitgliederschulen` `ms` on(`ms`.`MitgliederId` = `m`.`MitgliederId`)) left join `schulen` `s` on(`s`.`SchulId` = `ms`.`SchulId` and `s`.`Schulname` <> 'WTFB')) left join `schulleiterschulen` `ss` on(`ss`.`SchulId` = `s`.`SchulId`)) left join `schulleiter` `sl` on(`sl`.`LeiterId` = `ss`.`LeiterId`)) left join `mitgliederschulen` `msc` on(`msc`.`MitgliederId` = `m`.`MitgliederId`)) left join `schulen` `sc` on(`sc`.`SchulId` = `msc`.`SchulId`)) left join `disziplinen` `scd` on(`scd`.`DispId` = `sc`.`Disziplin`)) left join `maxgrad` `mg` on(`mg`.`MitgliedId` = `m`.`MitgliederId`)) left join `grade` `g` on(`g`.`gradId` = `mg`.`Grad`)) left join `disziplinen` `dd` on(`dd`.`DispName` = `g`.`DispName`)) left join `mitgliedergrade` `mgg` on(`mgg`.`GradId` = `mg`.`Grad` and `mgg`.`MitgliedId` = `m`.`MitgliederId`)) where 1 = 1 group by `m`.`MitgliederId`;
--mitgliederliste_o 	
CREATE VIEW `mitgliederliste_o` AS select `m`.`MitgliederId` AS `MitgliederId`,`m`.`MitgliedsNr` AS `MitgliedsNr`,`m`.`Vorname` AS `Vorname`,`m`.`Name` AS `Name`,`s`.`Schulname` AS `Schulname`,`sl`.`LeiterName` AS `LeiterName`,group_concat(distinct `d`.`DispKurz` separator ', ') AS `DispName` from ((((((`mitglieder` `m` left join `mitgliederschulen` `ms` on(`ms`.`MitgliederId` = `m`.`MitgliederId`)) join `schulen` `s` on(`s`.`SchulId` = `ms`.`SchulId`)) join `schulleiterschulen` `ss` on(`ss`.`SchulId` = `s`.`SchulId`)) join `schulleiter` `sl` on(`sl`.`LeiterId` = `ss`.`LeiterId`)) left join `mitgliederdisziplinen` `md` on(`md`.`MitgliedId` = `m`.`MitgliederId`)) join `disziplinen` `d` on(`d`.`DispId` = `md`.`DisziplinId`)) where 1 group by `md`.`MitgliedId`; 
--mitgliederzahl1 	
CREATE VIEW `mitgliederzahl1` AS select `t`.`jahr` AS `jahr`,`t`.`monat` AS `monat`,(select count(0) from `mitgliederschulen` `m1` where year(`m1`.`Von`) = `t`.`jahr` and month(`m1`.`Von`) = `t`.`monat` and `m1`.`SchulId` = `m2`.`SchulId`) AS `Eintritt`,(select count(0) from `mitgliederschulen` `m1` where year(`m1`.`Bis`) = `t`.`jahr` and month(`m1`.`Bis`) = `t`.`monat` and `m1`.`SchulId` = `m2`.`SchulId`) AS `Austritt`,(select count(0) from `mitgliederschulen` `m1` where year(`m1`.`KuendigungAm`) = `t`.`jahr` and month(`m1`.`KuendigungAm`) = `t`.`monat` and `m1`.`SchulId` = `m2`.`SchulId`) AS `Kuendigung`,(select count(0) from `mitgliederschulen` `m1` where (year(`m1`.`Von`) = `t`.`jahr` and month(`m1`.`Von`) <= `t`.`monat` or year(`m1`.`Von`) < `t`.`jahr`) and (year(`m1`.`Bis`) = `t`.`jahr` and month(`m1`.`Von`) >= `t`.`monat` or year(`m1`.`Bis`) > `t`.`jahr` or year(`m1`.`Bis`) is null) and `m1`.`SchulId` = `m2`.`SchulId`) AS `Anzahl`,`m2`.`SchulId` AS `SchulId` from (`tally` `t` join `schulen` `m2`) group by `t`.`jahr`,`t`.`monat`,`m2`.`SchulId` order by `t`.`jahr`,`t`.`monat`;
--mitgliederzahl3 	
CREATE VIEW `mitgliederzahl3` AS select `t`.`jahr` AS `jahr`,`t`.`monat` AS `monat`,(select count(0) from `mitgliederschulen` `m1` where year(`m1`.`Von`) = `t`.`jahr` and month(`m1`.`Von`) = `t`.`monat` and `m1`.`SchulId` = `m2`.`SchulId`) AS `Eintritt`,(select count(0) from `mitgliederschulen` `m1` where year(`m1`.`Bis`) = `t`.`jahr` and month(`m1`.`Bis`) = `t`.`monat` and `m1`.`SchulId` = `m2`.`SchulId`) AS `Austritt`,(select count(0) from `mitgliederschulen` `m1` where year(`m1`.`KuendigungAm`) = `t`.`jahr` and month(`m1`.`KuendigungAm`) = `t`.`monat` and `m1`.`SchulId` = `m2`.`SchulId`) AS `Kuendigung`,`m2`.`SchulId` AS `SchulId` from (`tally` `t` join `schulen` `m2`) group by `t`.`jahr`,`t`.`monat`,`m2`.`SchulId` order by `t`.`jahr`,`t`.`monat`; 
--mitgliederzahlen 	
CREATE VIEW `mitgliederzahlen` AS select `t`.`jahr` AS `jahr`,`t`.`monat` AS `monat`,(select case when count(`m1`.`msID`) is null then 0 else count(`m1`.`msID`) end AS `Eintritt` from ((`mitgliederschulen` `m1` join `schulen` `s` on(`s`.`SchulId` = `m1`.`SchulId`)) join `disziplinen` `d` on(`d`.`DispId` = `s`.`Disziplin` and `d`.`DispKurz` = 'WT')) where year(`m1`.`Von`) = `t`.`jahr` and month(`m1`.`Von`) = `t`.`monat`) AS `WT-Eintritt`,(select case when count(`m1`.`msID`) is null then 0 else count(`m1`.`msID`) end AS `Eintritt` from ((`mitgliederschulen` `m1` join `schulen` `s` on(`s`.`SchulId` = `m1`.`SchulId`)) join `disziplinen` `d` on(`d`.`DispId` = `s`.`Disziplin` and `d`.`DispKurz` = 'WT')) where year(`m1`.`Bis`) = `t`.`jahr` and month(`m1`.`Bis`) = `t`.`monat`) AS `WT-Austritt`,(select case when count(`m1`.`msID`) is null then 0 else count(`m1`.`msID`) end AS `Eintritt` from ((`mitgliederschulen` `m1` join `schulen` `s` on(`s`.`SchulId` = `m1`.`SchulId`)) join `disziplinen` `d` on(`d`.`DispId` = `s`.`Disziplin` and `d`.`DispKurz` = 'WT')) where year(`m1`.`KuendigungAm`) = `t`.`jahr` and month(`m1`.`KuendigungAm`) = `t`.`monat`) AS `WT-Kuendigung`,(select case when count(`m1`.`msID`) is null then 0 else count(`m1`.`msID`) end AS `Eintritt` from ((`mitgliederschulen` `m1` join `schulen` `s` on(`s`.`SchulId` = `m1`.`SchulId`)) join `disziplinen` `d` on(`d`.`DispId` = `s`.`Disziplin` and `d`.`DispKurz` = 'E')) where year(`m1`.`Von`) = `t`.`jahr` and month(`m1`.`Von`) = `t`.`monat`) AS `E-Eintritt`,(select case when count(`m1`.`msID`) is null then 0 else count(`m1`.`msID`) end AS `Eintritt` from ((`mitgliederschulen` `m1` join `schulen` `s` on(`s`.`SchulId` = `m1`.`SchulId`)) join `disziplinen` `d` on(`d`.`DispId` = `s`.`Disziplin` and `d`.`DispKurz` = 'E')) where year(`m1`.`Bis`) = `t`.`jahr` and month(`m1`.`Bis`) = `t`.`monat`) AS `E-Austritt`,(select case when count(`m1`.`msID`) is null then 0 else count(`m1`.`msID`) end AS `Eintritt` from ((`mitgliederschulen` `m1` join `schulen` `s` on(`s`.`SchulId` = `m1`.`SchulId`)) join `disziplinen` `d` on(`d`.`DispId` = `s`.`Disziplin` and `d`.`DispKurz` = 'E')) where year(`m1`.`KuendigungAm`) = `t`.`jahr` and month(`m1`.`KuendigungAm`) = `t`.`monat`) AS `E-Kuendigung` from `tally` `t` group by `t`.`jahr`,`t`.`monat` order by `t`.`jahr`,`t`.`monat`

